version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgres'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      timeout: 20s
      retries: 10
  migration:
    image: node:20-alpine
    build: ./migration
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres:
    driver: local
